### ISSUE TITLE
Admin interface not reachable and doesn't go to command line

### ISSUE THREAD

**Issue by pieterhouwen** [bhdresh/Dejavu#1]
When I boot up the VM it's taking me to the login screen. I've tried root/root and root/toor but they didn't work. I also bridged the adapters, but I cannot get a connection to either one.

**Comment by pieterhouwen** [comment]
I'm using VirtualBox as my virtualization by the way, maybe that's useful to note, maybe not

**Comment by pieterhouwen** [comment]
I didn't RTFM, my apologies

**Comment by bhdresh** [comment]
@pieterhouwen, glad that you gave it a spin. If you still have issue with setting up the Dejavu VM, please refer to this video guide https://youtu.be/NOuEGa0241U

Thanks a lot.
