### ISSUE TITLE
Error in ps1 Script from Add Decoy to Domain Functionality

### ISSUE THREAD

**Issue by zms200** [bhdresh/Dejavu#10]
The Add Decoy to Domain function produces an erroneous ps1 command.

Generating an Add Decoy to Domain script for a domain called TestDomain.local and a decoy called SMBDecoy produces the following Powershell script:

Import-Module ActiveDirectory
New-ADComputer -Name SMBtest -DNSHostName SMBtest.TestDomain.local
dnscmd /recordadd TestDomain.local SMBtest A 192.168.215.43
dnscmd /recordadd 215.168.192.in-addr.arpa 43 PTR SMBtest.TestDomain.local

Running this on the Domain Controller produces an error saying that the domain doesn't exist. This is because the name of the domain is missing from the last line of the script. The last line should instead read:
dnscmd /recordadd TestDomain.local 215.168.192.in-addr.arpa 43 PTR SMBtest.TestDomain.local

**Comment by bhdresh** [comment]
Hi,

Thank you for the report.

Looking into it.

**Comment by bhdresh** [comment]
Hi,

Adding this into fix :)

**Comment by zms200** [comment]
Thanks!
