### ISSUE TITLE
Error in ps1 Script from Kerberoast HoneyAccount Functionality

### ISSUE THREAD

**Issue by zms200** [bhdresh/Dejavu#11]
The Kerberoast HoneyAccount functionality produces an erroneous PowerShell script. Generating a script with a service name of "RealService" and an SPN Name of RealSPN produced the following script:

`Import-Module ActiveDirectory
New-ADUser -Name "RealService" -SamAccountName "RealService" -DisplayName "RealService" -ServicePrincipalNames "RealSPN" -AccountPassword (ConvertTo-SecureString "FRPoc2oCIQ)CbOpw#1I$C%5qsnJ6Sv" -AsPlainText -Force) -Enabled $True -GivenName "RealService" -PasswordNeverExpires $True`

Running this script in PowerShell resulted in errors. I was able to fix the errors and successfully achieve creating of the service account by replacing `-ServicePrinicalName "RealSPN"` with `REAL/RealSPN.TestDomain.local` I also added `-UserPrincipalName realservice@TestDomain.local`, but I don't know if that was necessary.

**Comment by bhdresh** [comment]
Hi,

Thank you for the report.

Including this into fix :)

**Comment by bhdresh** [comment]
True, you need to use valid SPN syntax. Will add an example on UI.
