### ISSUE TITLE
Question: Preconfigured DejaVu images

### ISSUE THREAD

**Issue by semperfiyemx** [bhdresh/Dejavu#16]
Hello, @bhdresh I received the email to download Preconfigured images
I look forward to reviewing your product, it's certainly something I have been looking for and really like what you have done. 
However,  I have a question
1.  When a launch image in virtualbox, it's requesting creds as shown here. 

![Screen Shot 2021-07-10 at 7 55 49 PM](https://user-images.githubusercontent.com/87249372/125179085-e5c42080-e1b8-11eb-84f9-9d0f4d07c6ae.png)

Thank you

**Comment by bhdresh** [comment]
Hi @semperfiyemx,

Thanks for pointing this out.

Username: administrator 
Password: changepassword 

Will update email body to include creds.

Regards,
-Bhadresh
