### ISSUE TITLE
can you help me

### ISSUE THREAD

**Issue by agusdwimuladi** [bhdresh/Dejavu#2]
i have trouble from instalation

**Comment by bhdresh** [comment]
Hi,

Could you please elaborate your problem?

PS: Below is the video walk through of installation steps for your reference, 

https://m.youtube.com/watch?feature=youtu.be&v=NOuEGa0241U

Thanks a lot.

**Comment by bhdresh** [comment]
Hi,

Could you please elaborate your problem?

PS: Below is the video walk through of installation steps for your reference, 

https://m.youtube.com/watch?feature=youtu.be&v=NOuEGa0241U

Thanks a lot.

**Comment by bhdresh** [comment]
Hi,

Thank you for your comment. 

Could you please elaborate your problem?

PS: Below is the video walk through of installation steps for your reference,

https://m.youtube.com/watch?feature=youtu.be&v=NOuEGa0241U

Thanks a lot.

**Comment by bhdresh** [comment]
Hi,

Thank you for your comment.

Could you please elaborate your problem you are facing?

PS: Below is the video walk through of installation steps for your reference,

https://m.youtube.com/watch?feature=youtu.be&v=NOuEGa0241U

Thanks a lot.

**Comment by bhdresh** [comment]
Hi,

Thank you for your comment.

Could you please elaborate the problem you are facing? 

PS: Below is the video walk through of installation steps for your reference,

https://m.youtube.com/watch?feature=youtu.be&v=NOuEGa0241U

Thanks a lot.

**Comment by agusdwimuladi** [comment]
ok thankyou very much, 
can I ask for your email address, I want to ask questions.

**Comment by bhdresh** [comment]
Hi, please send your queries to me on bhdresh@dejavu.tech

Thanks a lot. 

Regards, 
-Bhadresh
