### ISSUE TITLE
changing time zone in UI 

### ISSUE THREAD

**Issue by wizhardhacker1** [bhdresh/Dejavu#29]
When changing time zone to any time zone or using any NTP you get error message  "wrong timezone"

**Comment by bhdresh** [comment]
Fixed the issue. Working on the patch.

**Comment by bhdresh** [comment]
Released patch.

### To upgrade Engine

Go to "Backup & Upgrade" and click on "Upgrade DejaVu Engine"

### To upgrade Console

Go to "Backup & Upgrade" and click on "Upgrade DejaVu Console"

Release detail: https://github.com/bhdresh/Dejavu/releases/tag/v12.0
