### ISSUE TITLE
about documentation

### ISSUE THREAD

**Issue by fullzlop** [bhdresh/Dejavu#33]
Hello, Dejavu Deception framework is working nice but do you guys building some quick start quide or some manual for this.? so why am I asking this cuz need some information how is working, how services are working etc ..

**Comment by bhdresh** [comment]
Hello, yes, we are working on getting the preliminary documents out by the end of this month.

**Comment by fullzlop** [comment]
Hello, Thanks for the reply.
Good luck for your further

**Comment by fullzlop** [comment]
one question, I'm using hydra tool to brute-forcing the decoy server and Dejavu's result is not showing its brute force, it's showing like Nmap result. please see from below. 
![image](https://user-images.githubusercontent.com/16883351/140252434-c938ac82-fd0e-458e-87f0-6699c5ad929c.png)
![image](https://user-images.githubusercontent.com/16883351/140252473-0c8387dc-9d40-4f4d-9631-05efc97d79ee.png)

**Comment by bhdresh** [comment]
Can you share information about the services configured in the decoy?

**Comment by fullzlop** [comment]
hello,  please see from below image. 
![image](https://user-images.githubusercontent.com/16883351/140672144-faa19656-7f68-4794-bf78-ce80435d4ecd.png)

**Comment by fullzlop** [comment]
other question is how to clean logs?

**Comment by fullzlop** [comment]
> one question, I'm using hydra tool to brute-forcing the decoy server and Dejavu's result is not showing its brute force, it's showing like Nmap result. please see from below. ![image](https://user-images.githubusercontent.com/16883351/140252434-c938ac82-fd0e-458e-87f0-6699c5ad929c.png) ![image](https://user-images.githubusercontent.com/16883351/140252473-0c8387dc-9d40-4f4d-9631-05efc97d79ee.png)

**For this how to differentiate the attack types. etc: brute force, nmap scanning ...**

**Comment by bhdresh** [comment]
You should receive failed FTP authentication alerts like below to derive performed activity. Click on magnifier icon next to the alert to analyze the PCAP.

![Screenshot from 2022-01-02 02-42-24](https://user-images.githubusercontent.com/8931885/147861700-1c1277d4-4223-43f0-b2e4-1376e6889482.png)
 
PS: Ensure your instance is upgraded to latest version v14.
