### ISSUE TITLE
On new install for Console: Fatal error: require(): Failed opening required 'includes/PHPMailer/src/Exception.php' 

### ISSUE THREAD

**Issue by iamtmehdi** [bhdresh/Dejavu#34]
After setting up VMs from the links in email, there is the following error when navigating to IP address hosting the Console for first time.

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/5580143/144489916-9208424f-a335-4003-814b-43b99ab5c7ba.png">

My colleague who set this up mentioned:
> Couple things I did: I changed networking to get IP addresses from dhcp and modified apache2 config to listen on all IP addresses (there were hardcoded IPs from manuals before)

Not sure if either is causing the "No such file" error.

**Comment by bhdresh** [comment]
Please try to change IP address of management interface using portal or using following commend on console:

/var/log/data/setup.sh <IP Address> <Subnet Mask> <Gateway>

PS: Adding a console menu in next version (v14) to allow changing management interface from console.

**Comment by bhdresh** [comment]
Console menu has been added in v14 to facilitate IP changes from console.
