### ISSUE TITLE
Update Dejavu

### ISSUE THREAD

**Issue by 64kbMa** [bhdresh/Dejavu#38]
Hello,

i use version 11 and want to upgrade to the newst. I have downloaded the upgrade.zip (11->12) and use the function "settings -> Backup&Upgrade -> Upgrade" I select the upgrade.zip on Dejavu engine and click "Upgrade Dejavu Enngine". I do the same on the
Dejavu Console and wait about 30 Min. Then i reboot the Engine and the Console and booth are always shows version 11.

What make i wrong?

It is possible to upgrade from version 11 directly to version 14?

With friendly Regards

Mathias

**Comment by BenUhlig** [comment]
I have a similar question to the last part here... I got the link for downloading 11 and I have updated to 14 by downloading the update file... are these cumulative or do I need to run 12 and 13 updates as well.

Thanks!

**Comment by 64kbMa** [comment]
Hello bhdresh,

thank you for your help, it works great!
