### ISSUE TITLE
Feature Request - Ability to ignore certain addresses from triggering alert

### ISSUE THREAD

**Issue by BenUhlig** [bhdresh/Dejavu#41]
We have a few systems (Zabbix, Tenable.SC, etc. that will scan the network and I see those triggering alerts. Is there a way to configure this to ignore these known systems so it does not trigger an alert?

TIA

**Comment by bhdresh** [comment]
Yes, it is possible,

1) To filter the search : Apply filter as below from Threat Analysis -> Active Attacks -> Search Filter

![filter](https://user-images.githubusercontent.com/8931885/164486934-3ae7e6d7-0da3-49dc-ab7b-3e1e4c82c1b6.jpg)

2) To filter for notification :  Apply filter as below from Threat Analysis -> Manage Notifications -> New Alert

![Selection_001](https://user-images.githubusercontent.com/8931885/164487662-d4f4f9f6-af22-4551-a620-c7d9e9c9af6c.png)
