### ISSUE TITLE
vlan settings / trunk problems

### ISSUE THREAD

**Issue by evilprime** [bhdresh/Dejavu#45]
Hey, i am running into some new wierd issues. 

I've got single vlan interface setup working but its not very feasible since we got a lot of vlans, so i am trying out the trunk option. I'm am trying a few different options now which involves making the incoming interface a trunk port and tag all the vlans,  but Dejavu aint seeing the vlans. I've tried it as a edge port and tag all the vlans but Dejavus doesn't see our vlans still, tried with reboots of host and vm's but no luck. Have been looking for documentation on this but can't find any. I've been looking at the virtualbox documentation on this but it doesn't help. 

Am i missing something in my setup?

**Comment by kalpesh9493** [comment]
Hi Evilprime,

are using VMware Platform to Deploy Dejavu then please Follow the below KB, I have done 4 to 5 Installations with This KB and all-time I getting Sucess...

https://github.com/bhdresh/Dejavu/blob/master/Engine_ESXI.pdf

**Comment by evilprime** [comment]
Hi, that one doesn't help me at all unfortunately. I was more thinkin of a guideline when it comes to the switch configuration in combination with Dejavu, becasue no matter what settings i use on the switch side, it doesn't list my available vlans in Dejavu :/

**Comment by bhdresh** [comment]
@evilprime ... the only reason I could think of this behavior is that decoy interface attached to Dejavu is not carrying tagged traffic.

Which virtualization platform are you using? vmware? Did you configure "Virtual Guest Tagging" (VGT). It basically means that the VLAN ID is stripped off at the Guest OS layer and not at the portgroup layer. In other words the VLAN trunk(multiple VLANs on a single wire) is extended to the virtual machine and the virtual machine will need to deal with it. 

You can use the ESXI configuration as stated @ https://kb.vmware.com/s/article/1004252

**Comment by evilprime** [comment]
Hi, i am using Virtualbox, and was using the youtube video i found for configuring Dejavu. It doesn't cover the actual configurations but it does mention the functionality. I am pretty sure the trunk port is configured correctly. In Virtualbox i am using the second interface, in bridged mode. Maybe i should try Vmware instead.

**Comment by evilprime** [comment]
i am now reading that the PCNET FAST III in virtualbox doesn't support vlan tagging, i'm am going to try a different adapter then.
