### ISSUE TITLE
Any chance for Hyper-V?

### ISSUE THREAD

**Issue by thekrugers** [bhdresh/Dejavu#46]
I converted the VMware disk images to VHDX and set up a test lab in Hyper-V. The images boot and work to some extent, but not completely. In essence, the engine can receive incoming packets from the virtual switch on eth1, but nothing goes out to the virtual switch from the engine.

I presume this has something to do with interface virtual1000 on the engine being in promiscuous mode. Is there any way around this, or do I need to keep looking for alternatives that work in Hyper-V?

**Comment by kalpesh9493** [comment]
Hi There,

to configured  Engine on Hyperv-V, you need to Create a Two Virtual Switch , Switch 1 will Give you a Engine GUI Access on Configured IP Address, Switch two will Mange your Decoy ( Switch 2 Need to Be Configured on Trunk Port ),

reference Link : https://blog.workinghardinit.work/2015/10/13/trunking-with-hyper-v-networking/

**Comment by kalpesh9493** [comment]
![propromiscuous mode](https://user-images.githubusercontent.com/67192133/182168125-036a0612-163d-438c-84b0-c01a727457a9.jpeg)

also please check the attached Screen shot for your ready Reference  ( to Configured promiscuous mode on Dejavu ETH1 )

**Comment by bhdresh** [comment]
@thekrugers ... Did you get Dejavu working on Hyper-V with above steps?

**Comment by thekrugers** [comment]
This has worked, thanks.
