### ISSUE TITLE
smtp gmail not working?

### ISSUE THREAD

**Issue by evilprime** [bhdresh/Dejavu#48]
Hi, 

firstly like to say that i am glad i got things running, the vlan tagging is working perfectly with Hypver-V. Looking forward to finally settings this up at work in production.

I remember settings this up on my test server at work using the production smtp server on port 25, and this worked. Now i am testing it in my home lab using the gmail smtp server on poort 587 and smtp.gmail.com but this doesn't seem to be working. Is this a known issue?

regards, 

Lennart

**Comment by kalpesh9493** [comment]
hi,

Use the IP Address of the SMTP Server instead of the FQDN Name and then Try, please. and check if it works or not.

the same error I was also facing at my lab with Office 365 at that time I replaced FQDN With an SMTP IP address and it is working okay.

Regsards
Kalpesh.

**Comment by evilprime** [comment]
Cool, will check tonight thanks.

**Comment by evilprime** [comment]
Hmm it doesn't seem to be working on my side using the ip address

**Comment by kalpesh9493** [comment]
Hi, Which Email Service are u using , is that 2 FA Enabled on That Used Email Address, if you then Create the APP Password and then use that password For Email Authentication in Dejavu.

Thanks & Regards,

With Best Regards,
Kalpesh Panchal

**Comment by evilprime** [comment]
ah thanks, this worked!
