### ISSUE TITLE
How run mailAlert.php engine file?

### ISSUE THREAD

**Issue by khoshniat** [bhdresh/Dejavu#52]
Hi
where is php command for call getopt() function in mailAlert.php?

**Comment by bhdresh** [comment]
What do you mean? getopt is php function

https://www.php.net/manual/en/function.getopt.php

**Comment by khoshniat** [comment]
Hi
I found it. It is in /etc/log.sh file. It's true?

**Comment by bhdresh** [comment]
Yes mail alert is triggered from log.sh
