### ISSUE TITLE
When is authenticated smtp to be reimplemented ?

### ISSUE THREAD

**Issue by Boleqs** [bhdresh/Dejavu#53]
Looking for how to use authentication with smtp for alerts, i've found (it seems) that it is currently not implemented, yet it apparently was at a time.
Am I right in this assumption ? If yes, is it to be introduced again, and is there a temporary solution that I can use ?

Thank you for this solution that works like a charm otherwise ! Waiting for your response.

**Comment by kalpesh9493** [comment]
Sure Will Check and Get back to you on this.

**Comment by bhdresh** [comment]
@Boleqs ... authentication is still supported. You can navigate to deviceSettings.php on Console and configure the SMTP details for alerts.

**Comment by Boleqs** [comment]
You're right, I was just confused with updates and was still on v11. I've got it right now, thanks for the answers anyway !
