### ISSUE TITLE
Change IP during installation

### ISSUE THREAD

**Issue by duisen0v** [bhdresh/Dejavu#59]
Is it possible to change default IP during installation process?

**Comment by bhdresh** [comment]
Yes it is possible to change default IP during installation or after installation from SSH console menu.

Setting it up on Virtual Box: [Video Guide](https://youtu.be/FhF6fT8OHjA)
    Setting it up on VMware ESXi (PDF Guides): [Console](https://raw.githubusercontent.com/bhdresh/Dejavu/master/Console_ESXI.pdf) and [Engine](https://raw.githubusercontent.com/bhdresh/Dejavu/master/Engine_ESXI.pdf)
