### ISSUE TITLE
[Question] add client decoy

### ISSUE THREAD

**Issue by nocomp** [bhdresh/Dejavu#7]
hi the dev team,
thxx a lot for this great tool, i have few questions for you if you don t mind:
before i ve used open canary, you install this sort of honeypot on rpi, and plug it here and there on your network. Because  i have like 150 different offices, it require a bit of organisation.

In the dashboard, i guess what i used to have on a rpi is what is called a client decoy, right?

if my dejavu server is on 192.168.56.102 how do you proceed to "deploy" decoy on other ip range?
i ve added a decoy client in the same ip range than the pc hosting the vm, can t reach it, doesn t work.
Can i from a single vm deploy virtual decoy on all my subnet?
thank you for your time, truelly appreciate.

**Comment by bhdresh** [comment]
Hi,

Appreciate your query, in Dejavu,

NIC 1 should be used as a management interface to connect to DejaVU web console.

NIC 2,3,4... can be configured as a Trunk interface where you could have the multiple VLANs terminating where you would like to place decoys. Once you have this setup, you could N/W Management option on DejaVU admin console to add these VLANs. You can then create new decoys on this VLANs.

Quick reference: https://www.youtube.com/watch?v=NOuEGa0241U&t=16s

Hope this will help. Let me know if you have any query or need more information.
